language: ruby
services:
- redis-server
cache: bundler
rvm:
  - 2.0.0
bundler_args: --without production
before_script:
- mysql -e 'create database freeza_test;'
script:
- bundle exec rake test_with_coveralls
